# Generated by Django 5.2.1 on 2025-07-25 13:07

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('todo', '0003_task'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Task',
        ),
    ]
